language: node_js
node_js:
  - "0.10"
script:
  - "npm run coveralls || echo 'not running on coveralls'"
  - "test $SAUCE_USERNAME && npm run zuul || echo 'not running on saucelabs'"
  - npm test
env:
  global:
    - secure: X4sfFLSN2ViCFVAsIZ0IzUW6z7H+V0MPiB3iw0wLqEQmuoE1PfIaVHFVXRV61Jy1WpWOJIfPAmC0oVqcQlkStSVxdO8iLcarYA4R2dXaUxvjPWEYigd+mRE5irI2i7fx37XG+2X5Gk7lTOlkOjdhXbdi1/lvjreuEV1JzlXNbgU=
    - secure: Xovq8l0iwXjzW2mT6bP28hQgL+sw0cb+jRkzKzL0ZH9rJCGcNKpwn2O2uL01BtwJaISnOBwM2gSpZrcahLpNzVOm+NHL6Rv4d8rhBpB+x0jPPNpJ4vsfgMJtaorCdAeP9zeIgUj0nkVEVaMozpvE6hd2UgNsdvtod4eEht9ukZI=
